language: cpp

compiler:
  - gcc
  - clang


sudo: false


env:
  - DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DWITH_ITK=false"
  - DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=false -DWITH_ITK=false"
addons:
  apt:
   sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
   packages:
    - libopencv-dev
    - libhdf5-serial-dev
    - libcairo2-dev
    - doxygen
    - doxygen-latex
    - graphviz
    - libgmp-dev
    - libgdcm2-dev 
    - libgraphicsmagick++1-dev
    - libqglviewer-dev
    - libinsighttoolkit3-dev
    - g++-4.8
    - gcc-4.8
    - libboost-dev
    - libboost-program-options-dev
    - libboost-system-dev


before_install:
  - if [ $CXX == "g++" ]; then export CXX="g++-4.8"  CC="gcc-4.8"  CCOMPILER="gcc-4.8" CXXCOMPILER="g++-4.8"; fi
  - export SRC_DIR="`pwd`"


before_script:
  - ccache -V && ccache --show-stats && ccache --zero-stats
  - 'echo "using gcc : : ccache $CXX : <cflags>-std=c11 <cxxflags>-std=c++11 ;" > ~/user-config.jam'
  - 'echo "using clang : : ccache $CXX : <cflags>-std=c11 <cxxflags>-std=c++11 ;" >> ~/user-config.jam'
  - cd $SRC_DIR
  - git clone git://github.com/DGtal-team/DGtal.git
  - cd DGtal
  - cmake . $DGTALTYPE  -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER  
  - make 
  - cd ..

script: 
   - cmake . -DCMAKE_BUILD_TYPE=Debug -DDGtal_DIR=$PWD/DGtal -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER  -DUSE_OPENCV=true
   - make

