language: cpp
dist: xenial
osx_image: xcode12.2

compiler:
  - gcc
  - clang

os:
  - linux
  - osx


env:
  - CONFIG="Debug,QGLVIEWER"
  - CONFIG="Debug"
  - CONFIG="DOCUMENTATION"


matrix:
  fast_finish: true
  exclude:
    - os: osx
      env: CONFIG="DOCUMENTATION"
    - compiler: gcc
      os: linux
      env: CONFIG="DOCUMENTATION"
    - os: osx
      compiler: gcc
      


addons:
  apt:
   sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
   packages:
    - libopencv-dev
    - libhdf5-serial-dev
    - libcairo2-dev
    - doxygen
    - doxygen-latex
    - graphviz
    - libgmp-dev
    - libgdcm2-dev 
    - libgraphicsmagick++1-dev
    - libqglviewer-dev
    - libinsighttoolkit3-dev
    - g++-4.8
    - gcc-4.8
    - libboost-dev
    - libboost-program-options-dev
    - libboost-system-dev


before_install:
  - if [ $CXX == "g++" ]; then export CXX="g++-4.8"  CC="gcc-4.8"  CCOMPILER="gcc-4.8" CXXCOMPILER="g++-4.8"; fi
  - export SRC_DIR="`pwd`"


before_script:
  - if [ $TRAVIS_OS_NAME == linux ]; then  source .travis/confCCLinux.sh; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then source .travis/install_deps_macos.sh; fi
  - DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=false -DWITH_ITK=false"
  - if [ $CONFIG == "Debug,QGLVIEWER" AND  $TRAVIS_OS_NAME == osx  ]; then export DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true -DWITH_QT5=true -DWITH_ITK=false "; fi
  - if [ $CONFIG == "Debug,QGLVIEWER" AND  $TRAVIS_OS_NAME == linux  ]; then export DGTALTYPE="-DBUILD_EXAMPLES=OFF -DDGTAL_BUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=Debug -DWITH_QGLVIEWER=true  -DWITH_ITK=false"; fi
  - cd $SRC_DIR
  - git clone git://github.com/DGtal-team/DGtal.git
  - cd DGtal   
  - if [ $TRAVIS_OS_NAME == osx ]; then cmake . $DGTALTYPE  -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER  -DWITH_QT5=true ; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then cmake . $DGTALTYPE  -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER ; fi
  - make 
  - cd ..

script: 
  - if [ $TRAVIS_OS_NAME == osx ]; then cmake . -DCMAKE_BUILD_TYPE=Debug -DDGtal_DIR=$PWD/DGtal -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER  -DUSE_OPENCV=false ; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then cmake . -DCMAKE_BUILD_TYPE=Debug -DDGtal_DIR=$PWD/DGtal -DCMAKE_CXX_COMPILER=$CXXCOMPILER -DCMAKE_C_COMPILER=$CCOMPILER  -DUSE_OPENCV=true; fi    
  - make

